# Generated by Django 4.0.2 on 2022-03-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('demo_link', models.CharField(blank=True, max_length=2000, null=True)),
                ('title', models.CharField(blank=True, max_length=2000, null=True)),
                ('is_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
